version: 2
jobs:
  build:
    branches:
      ignore: gh-pages 
    docker:
      - image: circleci/node:8
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - run:
          name: Install Hexo
          command: sudo npm install -g hexo-cli
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Generate static website
          command: |
            hexo clean
            hexo generate

            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            hexo deploy
